In [1]:
import json, random
f = open('customer.json')
data = json.load(f)
f = open('depo.json')
depo = json.load(f)
customer_count = len(data)
depo1 = depo[0]
depo1['name'] = "Depo-"+depo1['name']
depo1['demand'] = 0
pelanggan = []
pelanggan.append(depo1)
for j in range(0, customer_count):
    data[j]['demand'] = random.randint(10, 70)
    pelanggan.append(data[j])

with open('pelanggan.json', 'w') as outfile:
    json.dump(pelanggan, outfile)

In [3]:
import json, random
import numpy as np
import pandas as pd
import gmaps
import googlemaps

API_KEY = 'AIzaSyCDq2h9qLZ1zKRHMT5Qv2QBfGWL0sAKDzI'
gmaps.configure(api_key=API_KEY)
googlemaps = googlemaps.Client(key=API_KEY)

f = open('pelanggan.json')
data = json.load(f)

# make dataframe which contains vending machine location and demand
df = pd.DataFrame(data)
print(df)



# function for calculating distance between two pins
def _distance_calculator(_df):
    
    _distance_result = np.zeros((len(_df),len(_df)))
    _df['latitude-longitude'] = '0'
    for i in range(len(_df)):
        _df['latitude-longitude'].iloc[i] = str(_df.latitude[i]) + ',' + str(_df.longitude[i])
    
    for i in range(len(_df)):
        for j in range(len(_df)):
            
            # calculate distance of all pairs
            _google_maps_api_result = googlemaps.directions(_df['latitude-longitude'].iloc[i],
                                                            _df['latitude-longitude'].iloc[j],
                                                            mode = 'driving')
            # append distance to result list
            _distance_result[i][j] = _google_maps_api_result[0]['legs'][0]['distance']['value']
    
    return _distance_result

distance = _distance_calculator(df)
print(distance)

                                       name  latitude   longitude  demand
0   Depo-Gas Station - Pertamina - 34-15316 -6.293370  106.648566       0
1                                Customer 1 -6.308553  106.653698      46
2                                Customer 2 -6.306463  106.653170      26
3                                Customer 3 -6.313126  106.652578      26
4                                Customer 4 -6.314943  106.652226      27
5                                Customer 5 -6.312494  106.646621      16
6                                Customer 6 -6.301097  106.642021      56
7                                Customer 7 -6.303528  106.641497      26
8                                Customer 8 -6.314158  106.652149      30
9                                Customer 9 -6.309986  106.653968      56
10                              Customer 10 -6.300227  106.648346      65
11                              Customer 11 -6.296925  106.647788      46
12                              Custom

C:\Users\ypand\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


[[   0. 2724. 2588. ... 3882. 5144. 3618.]
 [2150.    0.  263. ... 5319. 2841. 4783.]
 [1887. 1256.    0. ... 5056. 3677. 4520.]
 ...
 [5101. 6112. 5976. ...    0. 6162. 6475.]
 [5953. 3792. 4033. ... 9121.    0. 8585.]
 [4714. 5138. 5002. ... 7203. 7558.    0.]]


In [4]:
np.savetxt('distance.txt', distance)

In [5]:
np.loadtxt('distance.txt')

array([[   0., 2724., 2588., ..., 3882., 5144., 3618.],
       [2150.,    0.,  263., ..., 5319., 2841., 4783.],
       [1887., 1256.,    0., ..., 5056., 3677., 4520.],
       ...,
       [5101., 6112., 5976., ...,    0., 6162., 6475.],
       [5953., 3792., 4033., ..., 9121.,    0., 8585.],
       [4714., 5138., 5002., ..., 7203., 7558.,    0.]])